### ISSUE TITLE
Possible issue with PyPi upload (package does not include several needed packages in requirements)

### ISSUE THREAD

**Issue by kdw2126** [Placekey/placekey-py#2]
First of all, thanks for building such a great tool for referencing the identity and location in space of different entities!

There seems to a mismatch between the requirements.txt file in the current GitHub repo (which works fine when installed to my machine) and the requires.txt file included in the source code of the PlaceKey-py package posted on PyPI.  

The GitHub requirements.txt includes _requests_, _ratelimit_, _backoff_, all of which are required to have the main contents of the API submodule work correctly. Thus, when I currently download the package from PyPi and try to call the API submodule, it immediately fails owing to not having downloaded ratelimit as well.

Just wanted to bring this to your attention in case it wasn't intention -- thanks for reading!

**Comment by felixsafegraph** [comment]
great point. thanks for reporting. will fix this now.

**Comment by felixsafegraph** [comment]
fixed with v0.0.6 - thanks!
